
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftPLUSMINUSleftTIMESDIVleftFUNCTIONFUNCNAMEnonassocUMINUSPLUS MINUS TIMES DIV LPAREN RPAREN FLOAT NUMBER MODULO POWER FUNCNAME BAR FUNCTIONexpr : expr BAR exprexpr : expr PLUS exprexpr : expr MINUS exprexpr : MINUS expr %prec UMINUSexpr : expr TIMES expr\n    | expr DIV expr\n    | expr MODULO expr\n    | expr POWER expr\n    expr : POWERexpr : NUMBERexpr : FLOATexpr : LPAREN expr RPARENexpr : FUNCTION FUNCNAME LPAREN expr RPARENexpr : FUNCNAME LPAREN RPAREN'
    
_lr_action_items = {'MINUS':([0,1,2,3,4,5,6,9,10,11,12,13,14,15,16,17,20,21,22,23,24,25,26,27,28,29,30,31,],[2,11,2,-9,-10,-11,2,2,2,2,2,2,2,2,-4,11,11,-2,-3,-5,-6,11,11,-12,2,-14,11,-13,]),'POWER':([0,1,2,3,4,5,6,9,10,11,12,13,14,15,16,17,20,21,22,23,24,25,26,27,28,29,30,31,],[3,15,3,-9,-10,-11,3,3,3,3,3,3,3,3,-4,15,15,-2,-3,-5,-6,15,15,-12,3,-14,15,-13,]),'NUMBER':([0,2,6,9,10,11,12,13,14,15,28,],[4,4,4,4,4,4,4,4,4,4,4,]),'FLOAT':([0,2,6,9,10,11,12,13,14,15,28,],[5,5,5,5,5,5,5,5,5,5,5,]),'LPAREN':([0,2,6,8,9,10,11,12,13,14,15,18,28,],[6,6,6,19,6,6,6,6,6,6,6,28,6,]),'FUNCTION':([0,2,6,9,10,11,12,13,14,15,28,],[7,7,7,7,7,7,7,7,7,7,7,]),'FUNCNAME':([0,2,6,7,9,10,11,12,13,14,15,28,],[8,8,8,18,8,8,8,8,8,8,8,8,]),'$end':([1,3,4,5,16,20,21,22,23,24,25,26,27,29,31,],[0,-9,-10,-11,-4,-1,-2,-3,-5,-6,-7,-8,-12,-14,-13,]),'BAR':([1,3,4,5,16,17,20,21,22,23,24,25,26,27,29,30,31,],[9,-9,-10,-11,-4,9,9,-2,-3,-5,-6,9,9,-12,-14,9,-13,]),'PLUS':([1,3,4,5,16,17,20,21,22,23,24,25,26,27,29,30,31,],[10,-9,-10,-11,-4,10,10,-2,-3,-5,-6,10,10,-12,-14,10,-13,]),'TIMES':([1,3,4,5,16,17,20,21,22,23,24,25,26,27,29,30,31,],[12,-9,-10,-11,-4,12,12,12,12,-5,-6,12,12,-12,-14,12,-13,]),'DIV':([1,3,4,5,16,17,20,21,22,23,24,25,26,27,29,30,31,],[13,-9,-10,-11,-4,13,13,13,13,-5,-6,13,13,-12,-14,13,-13,]),'MODULO':([1,3,4,5,16,17,20,21,22,23,24,25,26,27,29,30,31,],[14,-9,-10,-11,-4,14,14,-2,-3,-5,-6,14,14,-12,-14,14,-13,]),'RPAREN':([3,4,5,16,17,19,20,21,22,23,24,25,26,27,29,30,31,],[-9,-10,-11,-4,27,29,-1,-2,-3,-5,-6,-7,-8,-12,-14,31,-13,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expr':([0,2,6,9,10,11,12,13,14,15,28,],[1,16,17,20,21,22,23,24,25,26,30,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expr","S'",1,None,None,None),
  ('expr -> expr BAR expr','expr',3,'p_split_bar','simple_calculator.py',73),
  ('expr -> expr PLUS expr','expr',3,'p_add','simple_calculator.py',79),
  ('expr -> expr MINUS expr','expr',3,'p_sub','simple_calculator.py',84),
  ('expr -> MINUS expr','expr',2,'p_expr2uminus','simple_calculator.py',89),
  ('expr -> expr TIMES expr','expr',3,'p_mult_div_modulo_power','simple_calculator.py',94),
  ('expr -> expr DIV expr','expr',3,'p_mult_div_modulo_power','simple_calculator.py',95),
  ('expr -> expr MODULO expr','expr',3,'p_mult_div_modulo_power','simple_calculator.py',96),
  ('expr -> expr POWER expr','expr',3,'p_mult_div_modulo_power','simple_calculator.py',97),
  ('expr -> POWER','expr',1,'p_expr2POWER','simple_calculator.py',114),
  ('expr -> NUMBER','expr',1,'p_expr2NUM','simple_calculator.py',119),
  ('expr -> FLOAT','expr',1,'p_expr2FLOAT','simple_calculator.py',124),
  ('expr -> LPAREN expr RPAREN','expr',3,'p_parens','simple_calculator.py',129),
  ('expr -> FUNCTION FUNCNAME LPAREN expr RPAREN','expr',5,'p_def_function','simple_calculator.py',134),
  ('expr -> FUNCNAME LPAREN RPAREN','expr',3,'p_call_function','simple_calculator.py',140),
]
